#ifndef SHELL_RETURN_TYPES_H
	#define SHELL_RETURN_TYPES_H

#include "NanoShellConfig.h"

typedef enum
{
	SHELL_SUCCESS = 0,
	SHELL_FILE_NOT_FOUND,
	SHELL_INSUFFICIENT_ARGUMENTS_FOR_FILE,
	SHELL_INVALID_PARAMETERS,
	SHELL_LINKED_LIST_LIBRARY_FAILED,
	SHELL_GENERIC_BUFFER_LIBRARY_FAILED,

	#if (USE_SHELL_COMMAND_HISTORY == 1)
		SHELL_HISTORY_BUFFER_FAILURE,
	#endif // end of #if (USE_SHELL_COMMAND_HISTORY == 1)

	SHELL_INVALID_NUMBER_OF_BYTES_TRANSFERRED,
	SHELL_INPUT_GENERIC_BUFFER_OVERFLOW,
	SHELL_OUTPUT_GENERIC_BUFFER_OVERFLOW,
	SHELL_INVALID_DIRECTORY_NAME,
	SHELL_DIRECTORY_NAME_ALREADY_EXISTS,
	SHELL_FILE_NAME_ALREADY_EXISTS,
	SHELL_ARGUMENT_OVERFLOW,
	SHELL_INVALID_CHARACTER_FOUND,
	SHELL_OPERATION_FAILED_OUTPUT_USER_BUFFER,
	SHELL_NO_HELP_FILE_PRESENT,
	SHELL_FILE_NOT_EXECUTABLE,
	SHELL_FILE_NOT_WRITABLE,
	SHELL_FILE_NOT_READABLE,
	SHELL_FILE_NO_DESCRIPTION,
	NUMBER_OF_SHELL_RESULTS
}SHELL_RESULT;

#endif // end of #define SHELL_RETURN_TYPES_H
