#ifndef CD_COMMAND_H
	#define CD_COMMAND_H

#include "../NanoShell.h"

#if (EXTENDED_CD_SUPPORT == 1)
	#define CD_HELP_TEXT \
	\
	CD_COMMAND_NAME ": " CD_COMMAND_NAME " [dir]" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Change the shell working directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Changes the current directory to DIR.  If .. is used this denotes the parent directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "A period '.' denotes the current working directory ./ (current_working_directory)."  SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "A " SHELL_HOME_DIRECTORY_CHARACTER_STRING " goes to the home directory.  A - goes to the prior directory used in the last " CD_COMMAND_NAME "."  SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " /folder-1/folder2" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " ../" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " " SHELL_HOME_DIRECTORY_CHARACTER_STRING SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " -" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE
#else
	#define CD_HELP_TEXT \
	\
	CD_COMMAND_NAME ": " CD_COMMAND_NAME " [dir]" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Change the shell working directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Changes the current directory to DIR.  If .. is used this denotes the parent directory." SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "A period '.' denotes the current working directory ./ (current_working_directory)."  SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB "Examples:" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " /folder-1/folder2" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_TAB SHELL_TAB CD_COMMAND_NAME " ../" SHELL_DEFAULT_END_OF_LINE_SEQUENCE \
	SHELL_DEFAULT_END_OF_LINE_SEQUENCE
#endif // end of #if (EXTENDED_CD_SUPPORT == 1)

SHELL_RESULT cdCommandExecuteMethod(char* Args[], UINT32 NumberOfArgs, GENERIC_BUFFER* Buffer);

#endif // end of #ifndef CD_COMMAND_H